import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable, map, of, catchError } from 'rxjs';

import { Player } from '../models/player.model';
import { getNbaHeadshotUrl } from '../utils/headshot';

/** JSON shape produced by scripts/fetch_nba_players.py */
export interface NbaPlayerJson {
  id: string;
  name: string;
  headshotUrl: string;
  stats?: {
    ppg?: number | null;
    rpg?: number | null;
    apg?: number | null;
    mpg?: number | null;
  };
}

const DATA_URL = 'data/nba-players-2025-26.json';

@Injectable({ providedIn: 'root' })
export class NbaDataService {
  constructor(private http: HttpClient) {}

  /**
   * Load active 2025-26 NBA players with stats. Uses JSON generated by
   * scripts/fetch_nba_players.py. Falls back to empty array on 404 or error.
   */
  getPlayers(): Observable<Player[]> {
    return this.http.get<NbaPlayerJson[]>(DATA_URL).pipe(
      map((list) => (Array.isArray(list) ? list : []).map((p) => this.toPlayer(p))),
      catchError(() => of([]))
    );
  }

  private toPlayer(p: NbaPlayerJson): Player {
    const explicitUrl = p.headshotUrl?.trim();
    const headshotUrl =
      explicitUrl || getNbaHeadshotUrl(p.id);
    return {
      id: p.id,
      name: p.name,
      headshotUrl,
      stats: p.stats
        ? {
            ppg: p.stats.ppg ?? undefined,
            rpg: p.stats.rpg ?? undefined,
            apg: p.stats.apg ?? undefined,
            mpg: p.stats.mpg ?? undefined,
          }
        : undefined,
    };
  }
}
